const brands = {
    "nike": { sustainable: false, reason: "Fast fashion, labor exploitation, high carbon footprint" },
    "patagonia": { sustainable: true, reason: "Uses recycled materials, fair labor policies" },
    "h&m": { sustainable: false, reason: "Fast fashion, high waste production" },
    "tentree": { sustainable: true, reason: "Plants trees, ethical manufacturing" },
    "adidas": { sustainable: true, reason: "Uses recycled plastics, sustainable materials" },
    "uniqlo": { sustainable: false, reason: "Fast fashion, poor labor standards" },
    "everlane": { sustainable: true, reason: "Transparent pricing, ethical labor practices" },
    "zara": { sustainable: false, reason: "Fast fashion, environmental impact" },
    "levis": { sustainable: true, reason: "Sustainable denim production, recycled materials" },
    "the north face": { sustainable: true, reason: "Uses recycled materials, eco-friendly practices" },
    "luxottica": { sustainable: false, reason: "Labor exploitation, poor environmental practices" },
    "mango": { sustainable: false, reason: "Fast fashion, water waste" },
    "cos": { sustainable: true, reason: "Uses sustainable cotton, ethical practices" },
    "puma": { sustainable: true, reason: "Eco-friendly materials, animal welfare standards" },
    "jcrew": { sustainable: false, reason: "Uses synthetic materials, lacks transparency" },
    "burt's bees": { sustainable: true, reason: "Eco-friendly packaging, natural ingredients" },
    "l'oreal": { sustainable: false, reason: "Testing on animals, harmful chemicals in products" },
    "nestle": { sustainable: false, reason: "Child labor issues, environmental harm" },
    "new balance": { sustainable: false, reason: "Limited transparency, synthetic materials" },
    "columbia": { sustainable: true, reason: "Eco-friendly manufacturing, recycled fabrics" },
    "gap": { sustainable: false, reason: "Fast fashion, poor labor transparency" },
    "old navy": { sustainable: false, reason: "High waste production, cheap synthetic materials" },
    "banana republic": { sustainable: true, reason: "Improving sustainability practices, ethical labor" },
    "lululemon": { sustainable: false, reason: "Limited transparency, synthetic fabrics" },
    "prada": { sustainable: false, reason: "High carbon footprint, luxury waste" },
    "gucci": { sustainable: true, reason: "Carbon-neutral efforts, sustainable materials" },
    "balenciaga": { sustainable: false, reason: "High energy consumption, synthetic materials" },
    "burberry": { sustainable: true, reason: "Sustainable cotton, waste reduction efforts" },
    "armani": { sustainable: false, reason: "Lack of transparency, synthetic materials" },
    "versace": { sustainable: false, reason: "High carbon footprint, limited ethical sourcing" },
    "chanel": { sustainable: false, reason: "Luxury waste, no clear sustainability efforts" },
    "ralph lauren": { sustainable: true, reason: "Organic cotton, water conservation efforts" },
    "tommy hilfiger": { sustainable: true, reason: "Sustainable denim, eco-friendly production" },
    "calvin klein": { sustainable: false, reason: "Fast fashion, synthetic materials" },
    "diesel": { sustainable: false, reason: "High waste production, synthetic materials" },
    "supreme": { sustainable: false, reason: "Fast fashion model, excessive consumption" },
    "stüssy": { sustainable: true, reason: "Small-scale production, sustainable cotton" },
    "off-white": { sustainable: false, reason: "Luxury waste, limited sustainability efforts" },
    "balmain": { sustainable: false, reason: "High carbon footprint, animal-based materials" },
    "moncler": { sustainable: false, reason: "Animal-based materials, limited sustainability efforts" },
    "canada goose": { sustainable: false, reason: "Animal cruelty concerns, synthetic materials" },
    "arc'teryx": { sustainable: true, reason: "Recyclable materials, durable products" },
    "helly hansen": { sustainable: true, reason: "Eco-friendly waterproofing, sustainable materials" },
    "fjällräven": { sustainable: true, reason: "Uses organic and recycled materials, ethical production" },
    "carhartt": { sustainable: false, reason: "Limited transparency, mass production issues" },
    "dickies": { sustainable: false, reason: "Synthetic materials, lacks sustainability commitments" },
    "wrangler": { sustainable: true, reason: "Water-saving denim production, organic cotton" },
    "lee": { sustainable: true, reason: "Eco-friendly denim processing, ethical labor" },
    "g-star raw": { sustainable: true, reason: "Uses organic cotton, reduced water waste" },
    "tom ford": { sustainable: false, reason: "Luxury materials, unsustainable sourcing" },
    "hermès": { sustainable: false, reason: "Excessive animal-based materials, high carbon footprint" },
    "coach": { sustainable: true, reason: "Recycled leather initiatives, sustainable practices" },
    "kate spade": { sustainable: false, reason: "Limited transparency, synthetic materials" },
    "tory burch": { sustainable: true, reason: "Sustainable sourcing, eco-friendly production" },
    "under armour": { sustainable: false, reason: "High synthetic material use, poor transparency" },
    "asics": { sustainable: true, reason: "Eco-friendly production, recycled materials" },
    "vans": { sustainable: false, reason: "Limited sustainability commitments, synthetic materials" },
    "converse": { sustainable: true, reason: "Uses recycled materials, sustainability efforts" },
    "skechers": { sustainable: false, reason: "Mass production, poor transparency" },
    "aldo": { sustainable: true, reason: "Vegan leather options, sustainability goals" },
    "crocs": { sustainable: true, reason: "Recyclable materials, minimal waste production" },
    "birkenstock": { sustainable: true, reason: "Natural materials, sustainable production" },
    "dr. martens": { sustainable: true, reason: "Vegan leather options, ethical sourcing" }
};
